# pyright: reportUnknownMemberType=false, reportUnknownArgumentType=false, reportUnknownVariableType=false, reportUnknownLambdaType=false
"""Campaign operations used by the glue runtime."""

from typing import TYPE_CHECKING, Protocol

ObjectiveResult = tuple[bool, tuple[int, ...]]  # (met, (v1, v2, v3, v4)); notes/debrief_evaluation.md 2.1

from .glue import MissionRef

if TYPE_CHECKING:
    from .payments import CashTerms


class CampaignRuntime(Protocol):
    def add_cash(self, amount: int) -> None: ...

    def set_mission_cash(self, terms: "CashTerms | None") -> None: ...

    def is_unit_in_army(self, unit_id: int) -> bool: ...

    def is_unit_in_march(self, unit_id: int) -> bool: ...

    def add_reinforcements(self, unit_id: int, count: int) -> None: ...

    def join_mission(self, unit_id: int) -> None: ...

    def leave_mission(self, unit_id: int) -> None: ...

    def mark_pending_join(self, unit_id: int) -> None: ...

    def objective(self, letter: str) -> ObjectiveResult | None: ...

    def bonus_init(self) -> None: ...

    def bonus_adjust(self, delta: int) -> None: ...

    def select_mission(self, mission: MissionRef) -> None: ...
    def enable_book(self, book: int, index: int) -> None: ...

    def autosave(self, runtime_state: object) -> None: ...
