"""Campaign operations used by the glue runtime."""

from typing import Protocol

from .glue import MissionRef


class CampaignRuntime(Protocol):
    def add_cash(self, amount: int) -> None: ...

    def is_unit_in_army(self, unit_id: int) -> bool: ...

    def is_unit_in_march(self, unit_id: int) -> bool: ...

    def add_reinforcements(self, unit_id: int, count: int) -> None: ...

    def join_mission(self, unit_id: int) -> None: ...

    def leave_mission(self, unit_id: int) -> None: ...

    def mark_pending_join(self, unit_id: int) -> None: ...

    def objective(self, letter: str) -> tuple | None: ...

    def bonus_init(self) -> None: ...

    def bonus_adjust(self, delta: int) -> None: ...

    def select_mission(self, mission: MissionRef) -> None: ...

    def autosave(self, runtime_state: object) -> None: ...
