"""Parser for the game's text scripts: battles (.BTS) and armies (.MRC). Format description: FORMATS.md.

Usage:
  whscript.py <file.BTS|file.MRC>        summary of a single file
  whscript.py <file> --json              full typed view as JSON
  whscript.py --check <SCRIPT dir>       parses all files and checks the set:count counters

Layers:
  parse()        -> generic node tree (sections [X]...[END] and blocks addX:...endX:)
  load_battle()  -> typed view of a .BTS (field, objectives, objects, scenery, boundaries, armies, nodes)
  load_army()    -> typed view of a .MRC (list of armies with their units)
"""
import json, os, re, sys

# block opener -> closer (compared case-insensitively)
BLOCKS = {
    'addunit': 'endunit', 'addleader': 'endleader', 'addobject': 'endobject',
    'addnode': 'endnode', 'addboundary': 'endboundary', 'addrectangles': 'endrectangles',
}
CLOSERS = {v: k for k, v in BLOCKS.items()}
# the 9 s_move values = tabletop Warhammer profile
PROFILE = ('M', 'WS', 'BS', 'S', 'T', 'W', 'I', 'A', 'Ld')
# s_side[0] & 0x3F -> unit type; decoded from the ';S_RACE is ...' comments (dominant label)
RACE_TYPES = {
    0: 'Monster', 1: 'Human Infantry', 2: 'Human Cavalry', 3: 'Human Archers', 4: 'Dwarven Infantry',
    5: 'Dwarven Archers', 6: 'Elven', 7: 'Skaven', 8: 'Orc Infantry', 9: 'Orc Cavalry', 10: 'Orc Archers',
    11: 'Goblinoid', 12: 'Goblinoid Cavalry', 13: 'Goblinoid Archers', 14: 'Peasant',
    15: 'Human Artillery', 16: 'Human Artillery', 17: 'Human Artillery', 18: 'Orc Artillery', 19: 'Human Wizard',
}


def side_info(s_side):
    """Splits setstats:s_side = [type, size, initial size, ?].

    type: bit 7 = enemy side, bit 6 = NPC/neutral (hypothesis), bits 0-5 = unit type.
    """
    if not s_side:
        return None
    code = s_side[0]
    return {
        'code': code, 'enemy': bool(code & 0x80), 'npc': bool(code & 0x40),
        'type': RACE_TYPES.get(code & 0x3F, f'type {code & 0x3F}'),
        'size': s_side[1] if len(s_side) > 1 else None,
        'orgsize': s_side[2] if len(s_side) > 2 else None,
        'extra': s_side[3] if len(s_side) > 3 else None,
    }


# comments generated by the editor, not usable as a section label
AUTO_COMMENT = re.compile(r';\s*(unit|piece|collision object|script node)\s*\d+', re.I)


class ParseError(Exception):
    pass


def _node(kind, name, line):
    return {'kind': kind, 'name': name, 'line': line, 'label': None,
            'set': {}, 'stats': {}, 'cmds': [], 'children': []}


def parse(path):
    """Returns the root of the tree (the top-level section, e.g. BATTLESCRIPT or MERCARMY).

    Node: kind ('section' or a block name, e.g. 'addunit'), name, line,
    label (first comment of the section, e.g. 'Enemy Army'), set {key: text},
    stats {key: [int]}, cmds [(command, argument)], children [nodes].
    """
    with open(path, 'rb') as handle:
        text = handle.read().decode('latin-1')
    root, stack = None, []
    for no, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line:
            continue
        where = f"{os.path.basename(path)}:{no}"
        if line.startswith(';'):
            cur = stack[-1] if stack else None
            if (cur and cur['kind'] == 'section' and cur['label'] is None
                    and not cur['children'] and not AUTO_COMMENT.match(line)):
                cur['label'] = line[1:].strip()
            continue
        if line.startswith('['):
            m = re.match(r'\[(\w+)\]', line)
            if not m:
                raise ParseError(f"{where}: bad section header: {line!r}")
            if m.group(1).upper() == 'END':
                if not stack or stack[-1]['kind'] != 'section':
                    raise ParseError(f"{where}: [END] without an open section (or inside a block)")
                stack.pop()
                continue
            sec = _node('section', m.group(1).upper(), no)
            if stack:
                stack[-1]['children'].append(sec)
            elif root is None:
                root = sec
            else:
                raise ParseError(f"{where}: second top-level section")
            stack.append(sec)
            continue
        if ':' not in line:
            raise ParseError(f"{where}: line without ':': {line!r}")
        if not stack:
            raise ParseError(f"{where}: command outside a section")
        key, _, value = line.partition(':')
        lk, cur = key.lower(), stack[-1]
        if lk in BLOCKS:
            blk = _node(lk, value, no)
            cur['children'].append(blk)
            stack.append(blk)
        elif lk in CLOSERS:
            if cur['kind'] != CLOSERS[lk]:
                raise ParseError(f"{where}: {key} closes {cur['kind']!r}")
            stack.pop()
        elif lk == 'set':
            k, _, v = value.partition('=')
            cur['set'][k] = v
        elif lk == 'setstats':
            k, _, v = value.partition('=')
            cur['stats'][k] = _nums(v)
        else:
            cur['cmds'].append((key, value))
    if stack:
        raise ParseError(f"{os.path.basename(path)}: unclosed: {[n['kind'] + ':' + n['name'] for n in stack]}")
    if root is None:
        raise ParseError(f"{os.path.basename(path)}: empty file")
    return root


def write(node):
    """Serialize a parse() node tree back to .BTS/.MRC text; the inverse of parse().

    Round-trips semantically, not byte-for-byte: field order is normalised (label, set,
    setstats, cmds, children) and comments other than a section's own label are dropped,
    matching what parse() itself already discards. A written-then-parsed tree carries the
    same set/stats/cmds/children data as the original.
    """
    lines = []
    _write_node(node, lines)
    return "\n".join(lines) + "\n"


def _write_node(node, lines):
    # A label comment is the first line *inside* a section (parse() attaches it to
    # whichever section is already open when the comment line is read), never before a block.
    if node['kind'] == 'section':
        lines.append(f"[{node['name']}]")
        if node['label'] is not None:
            lines.append(f"; {node['label']}")
    else:
        lines.append(f"{node['kind']}:{node['name']}")
    for key, value in node['set'].items():
        lines.append(f"set:{key}={value}")
    for key, values in node['stats'].items():
        lines.append(f"setstats:{key}={','.join(str(v) for v in values)}")
    for key, value in node['cmds']:
        lines.append(f"{key}:{value}")
    for child in node['children']:
        _write_node(child, lines)
    lines.append("[END]" if node['kind'] == 'section' else f"{BLOCKS[node['kind']]}:")


# ---------------------------------------------------------------- helpers

def _num(s):
    s = s.strip()
    try:
        return int(s)
    except ValueError:
        try:
            return float(s)
        except ValueError:
            return s


def _nums(s):
    return [_num(x) for x in s.split(',')] if s.strip() else []


def _cmd(node, key, default=None):
    return next((v for k, v in node['cmds'] if k.lower() == key.lower()), default)


def resource_name(value):
    """Return the resource token before the script's optional ``,N`` variant suffix."""
    return (value or "").split(",", 1)[0].strip() or None


def _cmds(node, key):
    return [v for k, v in node['cmds'] if k.lower() == key.lower()]


def _has(node, key):
    return any(k.lower() == key.lower() for k, _ in node['cmds'])


def _sets(node):
    return {k: _num(v) for k, v in node['set'].items()}


def _flags(v):
    return [f for f in str(v).split('|') if f] if v not in (None, '') else []


def _sections(node, name):
    return [c for c in node['children'] if c['kind'] == 'section' and c['name'] == name]


def _section(node, name):
    found = _sections(node, name)
    return found[0] if found else None


def display_name(s):
    """Names in the scripts use '<' or '_' instead of spaces (Grudgebringer<Cavalry)."""
    return s.replace('<', ' ').replace('_', ' ')


def find_ci(directory, name):
    """Looks up a file case-insensitively (the scripts were written on Windows)."""
    name = name.replace('\\', '/').lstrip('/')
    want = os.path.join(directory, name).lower()
    for f in os.listdir(os.path.dirname(want) if os.path.isdir(os.path.dirname(want)) else directory):
        if os.path.join(directory, f).lower() == want:
            return os.path.join(directory, f)
    return None


# ---------------------------------------------------------------- typed view

def unit_view(n):
    leader = next((c for c in n['children'] if c['kind'] == 'addleader'), None)
    u = {
        'id': n['name'], 'name': display_name(n['name']),
        'hidden': _has(n, 'hidden'),
        'sprites': _cmd(n, 'troopsprites'), 'banner': _cmd(n, 'banner'),
        'set': _sets(n), 'stats': n['stats'],
        'spells': _cmds(n, 'addspell'), 'items': _cmds(n, 'addmagicitem'),
        'leader': None,
    }
    if 's_move' in n['stats']:
        u['profile'] = dict(zip(PROFILE, n['stats']['s_move']))
    if leader:
        u['leader'] = {
            'id': leader['name'], 'name': display_name(leader['name']),
            'portrait': _cmd(leader, 'leaderportrait'), 'sprites': _cmd(leader, 'troopsprites'),
            'stats': leader['stats'],
            'profile': dict(zip(PROFILE, leader['stats'].get('s_move', []))),
        }
    return u


def army_view(sec):
    return {'label': sec['label'], 'count': _num(sec['set'].get('count', '0')),
            'units': [unit_view(c) for c in sec['children'] if c['kind'] == 'addunit']}


def mission_view(sec):
    if sec is None:
        return None
    return {'deploy_troops': _has(sec, 'DeployTroops'),
            'objectives': [_nums(v) for v in _cmds(sec, 'Objective')]}


def load_army(path):
    root = parse(path)
    return {'file': os.path.basename(path), 'type': root['name'],
            'mission': mission_view(_section(root, 'MISSIONINFO')),
            'armies': [army_view(s) for s in _sections(root, 'UNITS')]}


def units_of(root):
    """Raw ``addunit`` nodes of every ``[UNITS]`` section, for callers that need the full node
    (e.g. to round-trip it through :func:`write`) rather than :func:`unit_view`'s trimmed view."""
    return [child for section in _sections(root, 'UNITS') for child in section['children']
            if child['kind'] == 'addunit']


def load_battle(path, with_merc=True):
    root = parse(path)
    field = _section(root, 'FIELD')
    fs = _sets(field)
    f = {
        'width': fs.get('x'), 'height': fs.get('y'), 'map': fs.get('map'),
        'merc': _cmd(field, 'loadmerc'), 'mesh': _cmd(field, 'loadmesh'),
        'palette': _cmd(field, 'loadpal'), 'script': _cmd(field, 'loadScript'),
        'planmap': _cmd(field, 'loadplanmap'), 'portrait_bg': _cmd(field, 'loadportbg'),
        'ambient_light': _nums(_cmd(field, 'Ambient light color', '')),
        'position': _nums(_cmd(field, 'Position', '')),
        'bank_angle': _nums(_cmd(field, 'Bank angle', '')),
        'camera': _num(_cmd(field, 'Camera', '')) if _has(field, 'Camera') else None,
        'view': {k: fs[k] for k in ('vx', 'vy', 'zoom') if k in fs},
    }
    dyn = _section(root, 'DYNAMIC_LOAD')
    load = {}
    for k, v in (dyn['cmds'] if dyn else []):
        load.setdefault(k.lower(), []).append(v)
    if dyn and _has(dyn, 'NoBirds'):
        load['nobirds'] = True

    objects = []
    for o in (_section(root, 'OBJECTS') or {'children': []})['children']:
        s = _sets(o)
        rects = [_nums(v) for c in o['children'] if c['kind'] == 'addrectangles' for v in _cmds(c, 'rect')]
        objects.append({**{k: s.get(k) for k in ('x', 'y', 'z', 'radius', 'dir')},
                        'status': _flags(s.get('status')), 'rects': rects})

    scen = _section(root, 'SCENERY')
    scenery = []
    for v in _cmds(scen, 'placefurniture') if scen else []:
        name, *xyd = v.split(',')
        x, y, d = (_num(t) for t in xyd)
        scenery.append({'name': name, 'x': x, 'y': y, 'dir': d})

    bnd = _section(root, 'BOUNDARIES')
    boundaries = [{'name': b['name'], 'lines': [_nums(v) for v in _cmds(b, 'AddLine')]}
                  for b in (bnd['children'] if bnd else []) if b['kind'] == 'addboundary']

    nodes = []
    for n in (_section(root, 'NODES') or {'children': []})['children']:
        s = _sets(n)
        nodes.append({**{k: s.get(k) for k in ('x', 'y', 'radius', 'dir', 'id')},
                      'status': _flags(s.get('status'))})

    battle = {
        'file': os.path.basename(path), 'field': f,
        'mission': mission_view(_section(root, 'MISSIONINFO')),
        'load': load, 'objects': objects, 'scenery': scenery,
        'boundaries': boundaries, 'armies': [army_view(s) for s in _sections(root, 'UNITS')],
        'nodes': nodes, 'merc': None,
    }
    if with_merc and f['merc']:
        p = find_ci(os.path.dirname(path) or '.', f['merc'])
        battle['merc'] = load_army(p) if p else {'missing': f['merc']}
    return battle


# ---------------------------------------------------------------- validation

def check(root):
    """Returns a list of mismatches between the counters stored in the file and its actual contents."""
    issues = []

    def expect(sec, what, actual):
        if 'count' in sec['set'] and _num(sec['set']['count']) != actual:
            issues.append(f"[{sec['name']}] line {sec['line']}: count={sec['set']['count']}, found {actual} {what}")

    def walk(sec):
        blocks = lambda kind: sum(1 for c in sec['children'] if c['kind'] == kind)
        # [OBJECTS] set:count is deliberately skipped: it never equals the number of addobject blocks
        # (in 25/54 files = objects + units, in the rest it deviates by -8..+9), see FORMATS.md
        if sec['name'] == 'NODES':
            expect(sec, 'addnode', blocks('addnode'))
        elif sec['name'] == 'UNITS':
            expect(sec, 'addunit', blocks('addunit'))
        elif sec['name'] == 'SCENERY':
            expect(sec, 'placefurniture', len(_cmds(sec, 'placefurniture')))
        elif sec['name'] == 'BOUNDARIES':
            expect(sec, 'AddBoundary', blocks('addboundary'))
            lines = sum(len(_cmds(c, 'AddLine')) for c in sec['children'] if c['kind'] == 'addboundary')
            if 'Lines' in sec['set'] and _num(sec['set']['Lines']) != lines:
                issues.append(f"[BOUNDARIES] line {sec['line']}: Lines={sec['set']['Lines']}, found {lines} AddLine")
        for c in sec['children']:
            if c['kind'] == 'section':
                walk(c)
    walk(root)
    return issues


def check_dir(directory):
    files = sorted(f for f in os.listdir(directory) if f.upper().endswith(('.BTS', '.MRC')))
    ok = 0
    for f in files:
        p = os.path.join(directory, f)
        try:
            issues = check(parse(p))
            (load_battle if f.upper().endswith('.BTS') else load_army)(p)
        except Exception as e:  # noqa: BLE001 - aggregated report
            print(f"ERROR {f}: {type(e).__name__}: {e}")
            continue
        if issues:
            print(f"WARN  {f}: " + "; ".join(issues))
        else:
            ok += 1
    print(f"{ok}/{len(files)} files without issues")


def summary(path):
    if path.upper().endswith('.MRC'):
        a = load_army(path)
        print(f"{a['file']}: [{a['type']}]")
        armies = a['armies']
    else:
        b = load_battle(path)
        f = b['field']
        print(f"{b['file']}: field {f['width']}x{f['height']}, mesh={f['mesh']}, DLL script={f['script']}, "
              f"map={f['planmap']}, player army={f['merc']}")
        if b['mission']:
            print(f"  objectives: {b['mission']['objectives']}")
        print(f"  collision objects: {len(b['objects'])}, scenery: {len(b['scenery'])}, "
              f"nodes: {len(b['nodes'])}, boundaries: {[x['name'] for x in b['boundaries']]}")
        armies = b['armies'] + ((b['merc'] or {}).get('armies') or [])
    for army in armies:
        print(f"  army '{army['label']}': {len(army['units'])} units")
        for u in army['units']:
            s = u['set']
            lead = f" (leader: {u['leader']['name']})" if u['leader'] else ''
            print(f"    - {u['name']:28s} sprite={u['sprites']!s:18s} pos=({s.get('x')},{s.get('y')}) "
                  f"dir={s.get('dir')} profile={u.get('profile')}{lead}")
    issues = check(parse(path))
    print("  counters: OK" if not issues else "  counters: " + "; ".join(issues))


def main(args=None):
    """Run the legacy command-line interface."""
    args = sys.argv[1:] if args is None else args
    if not args:
        print(__doc__)
    elif args[0] == '--check':
        check_dir(args[1])
    elif '--json' in args:
        p = next(a for a in args if a != '--json')
        view = load_army(p) if p.upper().endswith('.MRC') else load_battle(p)
        print(json.dumps(view, indent=1, ensure_ascii=False))
    else:
        summary(args[0])


if __name__ == '__main__':
    main()
